version: '3.7'
services:
  db:
    image: "postgres:latest"
    ports:
      - "5434:5432"
    volumes:
      - ./pgData:/var/lib/postgre/data
    env_file:
      - .env

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always